# Generated by Django 3.0.8 on 2020-09-03 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('original_blog', '0002_auto_20200903_0127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='keywords',
        ),
    ]
