# Generated by Django 3.0.8 on 2020-09-03 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('original_blog', '0003_auto_20200903_0429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='relation_posts',
        ),
    ]
